### ISSUE TITLE
code-gen: extend generated type for `T.number().convert()`

### ISSUE THREAD

**Issue by tjonger** [compasjs/compas#1047]
For the below definition the type `GroupSingleParams` is generated with `{ id: number }`. But id can also be a string because of the `.convert()`. Can we extend the type to `{ id: number | string }`?

```js
  R.get("/:id", "single")
      .params({ id: T.number().convert() })
      .response({}),
```

**Comment by dirkdev98** [comment]
Also applicable for `T.bool().convert()`

**Comment by dirkdev98** [comment]
Thanks for the bug report!
