### ISSUE TITLE
cli: don't show error when lacking ./scripts

### ISSUE THREAD

**Issue by kaliumxyz** [compasjs/compas#1591]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/25854553/152956641-6e2c50bf-ac8b-4966-8c4f-1a50ae9a05be.png">

feel free to close if this is intended behavior. Cli always shows `error` when a project lacks `./scripts` folder.

**Comment by dirkdev98** [comment]
Ah nice catch, thanks
