### ISSUE TITLE
store(sendTransformedImage): provide nextjs/image blurDataUrl

### ISSUE THREAD

**Issue by bjarn** [compasjs/compas#1891]
With the sendTransformedImage feature, it would be useful to also provide the blurDataUrl which must be a base64-encoded image.

NextJS will then be able to preview this blur whilst the original image is still downloading.

https://nextjs.org/docs/api-reference/next/image#blurdataurl

**Comment by dirkdev98** [comment]
Thanks for creating the issue!

I guess the trick here will be to allow passing a prop to `createOrUpdateFile` that directly (or most likely via a job) generates the small image. It should probably be a 10px jpg to be compatible with most clients. And we should directly store the base64 string in the `meta` of the file so we don't have to fetch it separately.

There are a few related things that we could then improve on;
- Supplying the job implementation to generate that image, like we do for `jobQueueInsights`.
- Standardising the response type for images and exposing a helper function to format a file to the response type. It could be something like `fileInfoToResponse(file, { fileUrl: string, secureFileOptions?: {}, }): { name: string, fileUrl: string, blurDataUrl?: string, ... }`
