### ISSUE TITLE
package.json is not defined by "exports"

### ISSUE THREAD

**Issue by rodymolenaar** [compasjs/compas#1921]
Currently it is impossible to run react-native's cli with Compas packages installed. Unless the `package.json` files for `@compas/cli`, `@compas/stdlib` and `@compas/code-gen` are updated manually after every `yarn install`.

The root cause and fix should be the same as used here: https://github.com/uuidjs/uuid/pull/449

**Comment by dirkdev98** [comment]
Related https://github.com/react-native-community/cli/issues/1168 &  https://github.com/react-native-community/cli/pull/1648
