### ISSUE TITLE
Add visuals to docs and repo README

### ISSUE THREAD

**Issue by Mitchell-Ryan** [compasjs/compas#1945]
https://we.tl/t-Hgl9X7JTyJ

What is supplied in the download?
- AI file (So someone can edit the logo if it's ever needed)
- EPS file (To use for printing)
- Banner for README (White background)
- Complete logo with font (Adobe font: Program OT - Medium) (Transparent background)
- Logo icon (Transparent background)
- Logo favicon (Transparent background)

**Comment by dirkdev98** [comment]
Love it,  thanks a lot! 

Are you willing to add these to the README and docs? Or should I add them? [Vitepress](https://vitepress.vuejs.org/), the docs generator that we use, currently only hosts the docs of their v1.0 rewrite. The docs for the version that we use can be found [here](https://github.com/vuejs/vitepress/tree/0a3f0ebe4d7d47bcbebc20cbfb075b99ad7961da/docs).

I am including [the download](https://github.com/compasjs/compas/files/9228962/compas-logo-assets.zip) here so we don't lose it.

**Comment by dirkdev98** [comment]
[compasjs-logo-v2.zip](https://github.com/compasjs/compas/files/9901229/compasjs-logo-v2.zip) updated
