### ISSUE TITLE
Localhost CORS headers for staging environment are missing from some responses

### ISSUE THREAD

**Issue by richardcornelissen** [compasjs/compas#2182]
We're running a staging deployment of our API on render which we also use for our frontend.
Since compasjs 0.0.191, the `compas proxy` command has been removed, requiring the frontend to connect to the staging API directly.
We've been noticing a lot of CORS errors locally since, which seem to be caused by a reused regex with the global flag enabled:
https://github.com/compasjs/compas/blob/734d57e5baba81bc315d487f2f11fab802c05fd0/packages/server/src/middleware/cors.js#L73

Global regexes are not stateless, which causes the `regex.text` function to return different results on reuse (see [this article](https://medium.com/codesnips/js-careful-when-reusing-regex-636b92c6bf07)).

## Reproduction
Run the following command multiple times
```sh
curl 'https://api.acc.opendeur.nl/_product/prices' \
  -H "Connection: close" \
  -H 'accept: application/json, text/plain, */*' \
  -H 'origin: http://localhost:3000' \
  --compressed --verbose
```

Looking at the response headers, half of them will not include the following headers:
```
access-control-allow-origin: http://localhost:3000
access-control-allow-credentials: true
```

## Workaround
Create a new originFn function
```js
import { environment, isStaging } from "@compas/stdlib";

/**
 * Determines CORS response header
 *
 * @type {NonNullable<NonNullable<NonNullable<Parameters<typeof import("@compas/server").getApp>[0]>["headers"]>["cors"]>["origin"]}
 */
export const originFn = (ctx) => {
  if (environment.CORS_URL !== undefined && environment.CORS_URL.length > 0) {
    // Use CORS_URL array provided via environment variables
    const allowedOrigins = (environment.CORS_URL || "").split(",");
    const localhostRegex = /^http:\/\/localhost:\d{1,6}$/i;

    if (isStaging()) {
      // Allow all localhost origins
      const header = ctx.get("origin");
      if (allowedOrigins.indexOf(header) !== -1) {
        return header;
      }

      if (localhostRegex.test(header)) {
        return header;
      }

      return undefined;
    }

    const header = ctx.get("origin");
    if (allowedOrigins.indexOf(header) !== -1) {
      return header;
    }

    return undefined;
  }
};
```

And set it with `getApp`
```js
import { getApp } from "@compas/server";
import { originFn } from "./cors.js";

/**
 * Create a basic Compas app
 */
export function createApp() {
  return getApp({
    headers: { cors: { origin: originFn } },
  });
}
```

**Comment by dirkdev98** [comment]
Thanks for the extensive issue, repro and workaround!

Note for future me (:)): 
I have checked other places where we use regexes in Compas, this seems to be the only location where a regex with global flag is reused.
