### ISSUE TITLE
--watch always throws an EADDRINUSE when restarting

### ISSUE THREAD

**Issue by floristenhove** [compasjs/compas#2941]
Hi Dirk,

As you know, we're using Compas in our OpenDeur project. We're still on version 0.0.211 and hope to upgrade to the latest version somewhere in the next couple of months. One thing that currently doesn't work well for us is the file watcher. We always get an error about the port being in use when the server is restarted, resulting in making the watch functionality useless. I couldn't find anything in the changelog or the GitHub issues about this. We might've missed some configuration, so any help is much appreciated.

Command: `yarn compas run api --watch`

```js
// config/compas.json

{
  "cli": {
    "globalWatchOptions": {
      "extensions": ["js", "ts", "json"].
      "ignorePatterns": ["__fixtures__"]
    }
  }
}
```

Error
```
11:00:18.347 error[api] {
  type: 'uncaughtException',
  error: {
    name: 'Error',
    message: 'listen EADDRINUSE: address already in use :::3001',
    stack: [
      'at Server.setupListenHandle [as _listen2] (node:net:1751:16)',
      'at listenInCluster (node:net:1799:12)',
      'at Server.listen (node:net:1887:7)',
      'at Application.listen (/Users/floris/dev/opendeur-monorepo/node_modules/koa/lib/application.js:82:19)',
      'at main (file:///Users/floris/dev/opendeur-monorepo/opendeur-backend/scripts/api.js:22:7)',
      'at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
    ]
  },
  origin: 'uncaughtException'
}
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (node:net:1751:16)
    at listenInCluster (node:net:1799:12)
    at Server.listen (node:net:1887:7)
    at Application.listen (/Users/floris/dev/opendeur-monorepo/node_modules/koa/lib/application.js:82:19)
    at main (file:///Users/floris/dev/opendeur-monorepo/opendeur-backend/scripts/api.js:22:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1778:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 3001
}

Node.js v18.17.1
11:00:18.366 info[index] { message: 'Process exited', code: 1 }
```

**Comment by dirkdev98** [comment]
Hi @floristenhove, thanks for the detailed issue.

I am unable to reproduce this on both v0.0.211 and on latest with the following;

```js
import { getApp } from "@compas/server";
import { mainFn, spawn } from "@compas/stdlib";

mainFn(import.meta, main);

function main() {
  const app = getApp({});

  app.use((ctx, next) => {
    ctx.body = "Hi 3";
    return next();
  });

  app.listen(3001);

  // spawn("watch", ["docker", "top", "compas-postgres-12"], {
  //   stdio: "ignore",
  //   shell: true,
  // });
  spawn("watch", ["docker", "ps"], {
    stdio: "ignore",
    shell: true,
  });
}
```

Do you have any custom exit listeners / spawned child processes which could prevent or slowdown the exit?

**Comment by floristenhove** [comment]
Thank you for helping out. As far as I can see, we don't have any custom exit listeners or spawned child processes. We do boot some services, but they shouldn't delay the exit, I presume. I understand it's hard to resolve this issue without being able to reproduce it. Is there anything I can provide to make this easier?

**Comment by dirkdev98** [comment]
Also no luck here on reproducing it in various private projects on the latest version.

So indeed, a (minimal) reproduction would be key to finding out what's going on.

**Comment by floristenhove** [comment]
We found out what was causing this. It was indeed another process (puppeteer) that was running. My bad, I missed that. Thanks for your help.

**Comment by dirkdev98** [comment]
Glad you found the issue!
