### ISSUE TITLE
store: job queue support timeout on handler runs

### ISSUE THREAD

**Issue by dirkdev98** [compasjs/compas#651]

**Comment by dirkdev98** [comment]
Was an application issue. However if we had timeouts for the handler we may have spotted the issue earlier.

@tjonger  what do you think about a global timeout on the 'handler' invocation? Then application specific code can always add smaller timeouts themselves on specific jobs if they need to

**Comment by tjonger** [comment]
@dirkdev98 Sounds reasonable! To what status will the job be updated once the timeout is hit?

**Comment by dirkdev98** [comment]
I guess an error log and retry will be fine. Once we have the max retries in we should be golden

**Comment by dirkdev98** [comment]
See #424
