### ISSUE TITLE
code-gen: Windows support

### ISSUE THREAD

**Issue by arunesh90** [compasjs/compas#673]
Encountering the following error when trying to generate code

```
16:43:54.961 error[generate] {
  type: 'error',
  message: 'Error caught from callback passed in `mainFn`',
  error: {
    name: 'Error',
    message: 'ENOENT: no such file or directory, mkdir',
    stack: [
      'at mkdirSync (node:fs:1009:3)',
      'at writeFiles (file:///C:/Users/arune/Desktop/Projects/Lightbase/opendeur-backend-wsl/node_modules/@compas/code-gen/src/generator/index.js:211:5)',
      'at generate (file:///C:/Users/arune/Desktop/Projects/Lightbase/opendeur-backend-wsl/node_modules/@compas/code-gen/src/generator/index.js:161:3)',
      'at App.generate (file:///C:/Users/arune/Desktop/Projects/Lightbase/opendeur-backend-wsl/node_modules/@compas/code-gen/src/App.js:310:26)',
      'at main (file:///C:/Users/arune/Desktop/Projects/Lightbase/opendeur-backend-wsl/scripts/generate.js:23:13)'
    ]
  }
}
```

Compas version: 0.0.115

**Comment by dirkdev98** [comment]
Node.js 'path' module allows for forward slashes in paths on Windows. However, when `path.xxx` operations are done it will use `path.sep`. This clashes with what some internal path transfomers expect. By forcing use of posix based join, this may be fixed.

Will create a new release early next week

**Comment by dirkdev98** [comment]
Closing this. If anyone wants to add windows support, you are very welcome! If need you need any help deciphering internal errors thrown because of this, feel free to ping me.
