### ISSUE TITLE
code-gen: improve 'splitability' of the apiClient when `isBrowser: true`

### ISSUE THREAD

**Issue by dirkdev98** [compasjs/compas#730]
We generate a closure around the api calls, to help with getting a 'unique' api client for SSR. This however prevents some chunk optimizations that can be done for the client side chunks.

**Comment by dirkdev98** [comment]
Currently looks something like:

```js
function newApiClient() {
  const foo = {
     bar: () => {... },
     baz: () => {... },
  };

  const quix = {
     bar: () => {... },
     baz: () => {... },
  };

  return {
    quix,
    foo,
  };
}
```

In combination with the generated hooks you get something like;

```ts
const { foo } = useApi();
await foo.bar();
// Or
const api = useApi();
api.quix.baz();
```

**Comment by dirkdev98** [comment]
The easiest way would be to pass an Axios instance as the first argument to the api call functions, in combination with a function that adds the interceptors for `x-request-id`;

```ts
export async function apiFooBar(axios: AxiosInstance, parms, body) {
 // ...
}
```

Then we still need a `useApi()` hook but use it to store the Axios instance so the react-query hooks can use it.

Was thinking about some other options, but would rather keep it simple :)

/cc @tjonger , @rodymolenaar

**Comment by rodymolenaar** [comment]
> The easiest way would be to pass an Axios instance as the first argument to the api call functions, in combination with a function that adds the interceptors for `x-request-id`;
> 
> ```ts
> export async function apiFooBar(axios: AxiosInstance, parms, body) {
>  // ...
> }
> ```
> 
> Then we still need a `useApi()` hook but use it to store the Axios instance so the react-query hooks can use it.
> 
> Was thinking about some other options, but would rather keep it simple :)
> 
> /cc @tjonger , @rodymolenaar

Is this optimization solely for SSR or those this also provide build size improvements?

**Comment by dirkdev98** [comment]
> Is this optimization solely for SSR or those this also provide build size improvements?

Mainly done for build size improvements.  Doesn't improve much for SSR I think.
I think the last time you pulled up the chunk-analyzer (?) the generated api client was a big offender. By splitting it up in all separate functions all pages can fully tree-shake the unecesary api calls out.


So this


```ts
function newApiClient(axios: AxiosInstance) {
  let _requestId: string|undefined = undefined;
  // Setup X-Request-Id handling

  const foo = {
     bar: () => {... },
     baz: () => {... },
  };

  const quix = {
     bar: () => {... },
     baz: () => {... },
  };

  return {
    quix,
    foo,
  };
}
```

Turns in to this:

```ts

// X-Request-Id helper
function checkInterceptors() {}

export async function apiFooBar(axios: AxiosInstance, parms, body) {
  checkInterceptors();

 return axios.request({ ... });
}


export async function apiFooBaz(axios: AxiosInstance, parms, body) {
  checkInterceptors();

 return axios.request({ ... });
}
```

It's going to look a lot like the generated hooks file.

**Comment by rodymolenaar** [comment]
> The easiest way would be to pass an Axios instance as the first argument to the api call functions, in combination with a function that adds the interceptors for `x-request-id`;
> 
> ```ts
> export async function apiFooBar(axios: AxiosInstance, parms, body) {
>  // ...
> }
> ```
> 
> Then we still need a `useApi()` hook but use it to store the Axios instance so the react-query hooks can use it.
> 
> Was thinking about some other options, but would rather keep it simple :)
> 
> /cc @tjonger , @rodymolenaar

I've looked at this for a while and have concluded that passing the Axios instance as the first parameter is the simplest solution. 

However, I'm not sure about the `apiFooBar` naming. IMHO a `generated/api/foo.ts` containing a `bar()` function has preference, because it allows easier discovery of functions and import grouping.

Not sure how much impact this would have, since all other hooks, types, validators, etc. should probably be grouped the same.

Since this is going to be a big breaking change, we might as well do some house keeping of the generated directory.

What are your views @dirkdev98?

**Comment by dirkdev98** [comment]
> I've looked at this for a while and have concluded that passing the Axios instance as the first parameter is the simplest solution.

Noice, was implementing this already :)

> However, I'm not sure about the `apiFooBar` naming. IMHO a `generated/api/foo.ts` containing a `bar()` function has preference, because it allows easier discovery of functions and import grouping.

Splitting the generated files in `$outputDirecotry/[group]/[generator].{ts,js}` and skipping `index.js` generation seems fine by me, but shortening the exported names gives most likely a worse experience. You would see `list` and maybe it's a validator, maybe it's an api call, and is it a list of users or a list of some other entity?

I don't have other 'breaking' housekeeping tasks planned. But other suggestions are welcome!

**Comment by dirkdev98** [comment]
Part one done in #736 .

> Splitting the generated files in $outputDirecotry/[group]/[generator].{ts,js}

Extracted to #755
