### ISSUE TITLE
code-gen: split output in `$outputDirectory/$group/$generator`

### ISSUE THREAD

**Issue by dirkdev98** [compasjs/compas#755]
For easier discoverability of the functionality.
To solve things like the anonymous validators that are used over the different groups, we reserve `common` as a group name and use that directory for specific shared output

**Comment by dirkdev98** [comment]
@rodymolenaar  @tjonger any prefs on generating `index.js` files?

**Comment by rodymolenaar** [comment]
> @rodymolenaar @tjonger any prefs on generating `index.js` files?

Can you be more specific about what kind of preferences?
