### ISSUE TITLE
code-gen: throw error on inferred array with multiple values passed in

### ISSUE THREAD

**Issue by dirkdev98** [compasjs/compas#762]
ie `["Monday", "Tuesday"]` resolves to `T.array().values(T.string().oneOf("Monday")))`

**Comment by tjonger** [comment]
@dirkdev98 I guess this one is quite specific but a generic type guard on all `.keys()` or `.values()` methods, only accepting `TypeBuilderLike` instances would also be really helpful. And prevent any unforeseen code paths / debug rounds?

**Comment by dirkdev98** [comment]
We already throw here if no type can be inferred https://github.com/compasjs/compas/blob/main/packages/code-gen/src/builders/utils.js#L35

I guess this ticket is relatively easy by changing the `value.length !== 0` to `value.length === 1` here https://github.com/compasjs/compas/blob/main/packages/code-gen/src/builders/utils.js#L48
