### ISSUE TITLE
code-gen: ensure generated validator for `T.number()` acknowledge postgres max integer size. 

### ISSUE THREAD

**Issue by tjonger** [compasjs/compas#786]
> PostgresError messagevalue "105131312312321" is out of range for type integer
 
 The generated is integer check does not take the value (size) into account. This could break queries or other stuff. 
 
 current check:
 
![image (1)](https://user-images.githubusercontent.com/2414721/113706429-f5762980-96de-11eb-99b9-f3b7e8fe5623.png)

  
Steps to reproduce;
```node
 R.post("/foo", "bar")
    body({
        number: T.number()
    })
```

pass in value `105131312312321` (example) value. 
![image (2)](https://user-images.githubusercontent.com/2414721/113706544-176fac00-96df-11eb-9035-0e1fc097e07a.png)

**Comment by dirkdev98** [comment]
What would be the expected outcome:
`- 2,147,483,647 ->  2,147,483,647` signed integer
or `- 2,147,483,647 -> 4,294,967,295` to account for both signed and unsigned ints?
