### ISSUE TITLE
store: handlerTimeout per job or handler instead of the queue worker itself

### ISSUE THREAD

**Issue by tjonger** [compasjs/compas#810]
Most of our jobs should acknowledge the default timeout (30 seconds), but for some jobs we know they can (and may) run for multiple minutes. For example image/video upload tasks. Should be helpful to override the timeout on a job by job base (or handler base (cover job types).

```node
const queueWorker = new JobQueueWorker(sql, {
    handler: async (event, sql, job) => {
      // suggestion set handler here, based on the job object
      await handleJob(event, sql, job);
    },
    handlerTimeout: 30, // keep this for default
  });
```

**Comment by dirkdev98** [comment]
Soemthing like: 

```
handlers: {
  key: myHandler
  otherKey: {
     handler: myHandler,
     timeout: 50000
  }
```

**Comment by tjonger** [comment]
Yes, like that. Or passing the workerOptions itself in (and decided based on the jobName). 

By doing we always have 5 minutes for that job and have the ability to override this during job creation for special/edge cases. 

```node
const queueWorker = new JobQueueWorker(sql, {
  handler: async (event, sql, job, workerOptions) => {
    switch (job.name) {
      case 'job.uploadingGigAndGigsOfData':
        workerOptions.handlerTimeout = job.data.timeout ?? 90 * 5; // 5 min
        break;
      default:
        break;
    }
    
    // suggestion set handler here, based on the job object
    await handleJob(event, sql, job);
  },
  handlerTimeout: 30, // keep this for default
});
```

**Comment by dirkdev98** [comment]
Once we call the handler, the timeout is already running. so the above won't be possible

**Comment by dirkdev98** [comment]
As discussed IRL, I preferred to make defining a custom timeout on job creation a special case via `addJobWithCustomTimeoutToQueue`. See https://compasjs.com/features/background-jobs.html for the current 'add' functions exported from `@compas/store`.

Does this cover the full usecase that you had?

**Comment by tjonger** [comment]
This is exactly what I needed. Thanks 👍
