### ISSUE TITLE
insight: move to other Compas packages

### ISSUE THREAD

**Issue by dirkdev98** [compasjs/compas#850]
Contemplating this for a while:

- Logger and writers can go in @compas/stdlib
- eventStart, stop, rename, etc can go in @compas/stdlib
- bytesToHumanReadable, printProcessMemoryUsage can go in @compas/stdlib
- postgresTableSizes can go in @compas/store

The main reason being that the logger is duplicating env related stuff like checking `isProduction`, keeping an environment cache.  Another reason is that stdlib already depends on insight cause it needs the logger in for example `mainFn`.

Some downsides:
- Smaller packages often have a clear / better api
- Stdlib becomes quite a lot bigger
- it's a breaking change, with a quick fix:
  `find ./ -type f -name "*.js" -exec sed -i 's/@compas\/insight/@compas\/stdlib/g' {} \;` with a `yarn compas lint` to combine imports

/cc @tjonger , @rodymolenaar

**Comment by tjonger** [comment]
Makes sense. Don't see any down side. This wil only make compas utils way more consistent
