### ISSUE TITLE
code-gen: support T.file().mimeTypes() or T.file().fileType()

### ISSUE THREAD

**Issue by dirkdev98** [compasjs/compas#885]
Not sure yet which one to support;

1. mime types:

```js
T.file().mimeTypes("application/json", "video/mp4");

// validator:
const mime = mime.getType(file.name);
if (!mimes.includes(mime)) {
  throw AppError.validationError("validator.file.unsupportedMime", { found: mime, allowed: [... ] });
}
```

2. file types

```js
import { fileType } from "@compas/store";

T.file().fileType(fileType.video);

// validator allows 
// - video/mp4
// - video/mov
// - ...
```

Using https://npmjs.com/package/mime

When using the fileType variant, we probably want to expose the file types via @compas/store most likely

**Comment by dirkdev98** [comment]
Probably preferring option 1, since some application may only want to support png's and not jpg files

**Comment by tjonger** [comment]
Great! Option 1 certainly, since options 2 does way too much in my opinion. But option 2 is still valid as wrapper in client scope
