### ISSUE TITLE
code-gen: Add query/mutation types to generated queries

### ISSUE THREAD

**Issue by owinter86** [compasjs/compas#934]
Update naming convention for generated queries/mutations for a more refined autocomplete/suggestions in IDE's and give the user a clearer understanding of the hook without navigating to the implementation.

`useSearchItem` to `useQuerySearchItem`
`useTodoUpdate` to `useMutationTodoUpdate`

**Comment by dirkdev98** [comment]
I find it hard to justify this breaking change. When the structure is controlled, names should already be descriptive enough to include a mutation eg `useTodoAdd`, `useTodoUpdate`, `useTodoRemove` and `useTodoSetComplete`. Thinking about putting this behind an option `useReactQueryHookPrefixes`.

**Comment by owinter86** [comment]
I think its ok, for our RN projects that are synced with Compas and the internal api's at Lightbase we will just conform the the already setup conventions, for external services that we use we may just continue with our own internal codegen as we would like to add more RN and internalised workflow specifics and maybe cleanup some of the overhead that is required for server rendered apps.
