### ISSUE TITLE
stdlib: include duration between eventStart and eventStop

### ISSUE THREAD

**Issue by arunesh90** [compasjs/compas#979]
It would be nice if in the logs the amount of time is included that it took for a event to be executed.
This would give a better overview of what events take longer than expected.

**Comment by dirkdev98** [comment]
Sounds good to me, we have 2 variants to put a `duration` value:

```json
{
  "name": "foo",
  "duration": 5,
  "callStack": [ { "type": "start", ... } ]
}
```

or add it to the existing `type: "start"`

```json
{
  "type": "start",
  "time": 00000,
  "duration": 5,
}
```

/cc @tjonger

**Comment by tjonger** [comment]
2th variant! Close to current imp and solves the goals
